# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cEtOJXTpjhl8AZ5Gcm0Zwem5Y1IXzuXd
"""

import os
import shutil
import random
import matplotlib.pyplot as plt

# --- CONFIGURATION ---
# Change this to where you uploaded the unzipped Kaggle dataset
SOURCE_DATA_DIR = '/content/drive/MyDrive/INFO813_Project/animal_dataset'
# This is where the YOLO-ready data will go
OUTPUT_DIR = '/content/drive/MyDrive/INFO813_Project/yolo_ready_data'

from google.colab import drive
drive.mount('/content/drive')

# --- 1. DATA ANALYSIS & VISUALIZATION ---
classes = [d for d in os.listdir(SOURCE_DATA_DIR) if os.path.isdir(os.path.join(SOURCE_DATA_DIR, d))]
class_counts = {}

for cls in classes:
    num_images = len(os.listdir(os.path.join(SOURCE_DATA_DIR, cls)))
    class_counts[cls] = num_images

# Plotting the visualization for your report
plt.figure(figsize=(20, 8))
plt.bar(class_counts.keys(), class_counts.values(), color='skyblue')
plt.xticks(rotation=90, fontsize=8)
plt.title('Distribution of Images per Animal Class')
plt.xlabel('Animal Classes')
plt.ylabel('Number of Images')
plt.tight_layout()
plt.savefig('/content/drive/MyDrive/INFO813_Project/class_distribution.png')
plt.show()

print(f"Total Classes: {len(classes)}")
print(f"Total Images: {sum(class_counts.values())}")
print("Visualization saved! Use this image in your report.")

# --- 2. DATA TRANSFORMATION (TRAIN/VAL SPLIT) ---
train_dir = os.path.join(OUTPUT_DIR, 'train')
val_dir = os.path.join(OUTPUT_DIR, 'val')

os.makedirs(train_dir, exist_ok=True)
os.makedirs(val_dir, exist_ok=True)

split_ratio = 0.8 # 80% for training, 20% for validation

for cls in classes:
    os.makedirs(os.path.join(train_dir, cls), exist_ok=True)
    os.makedirs(os.path.join(val_dir, cls), exist_ok=True)

    images = os.listdir(os.path.join(SOURCE_DATA_DIR, cls))
    random.shuffle(images) # Shuffle to ensure random distribution

    split_index = int(len(images) * split_ratio)
    train_images = images[:split_index]
    val_images = images[split_index:]

    # Copy files
    for img in train_images:
        shutil.copy(os.path.join(SOURCE_DATA_DIR, cls, img), os.path.join(train_dir, cls, img))
    for img in val_images:
        shutil.copy(os.path.join(SOURCE_DATA_DIR, cls, img), os.path.join(val_dir, cls, img))

print("✅ Data successfully split into Train and Val folders!")

# 1. Install the YOLO library
!pip install ultralytics

# 2. Import YOLO
from ultralytics import YOLO

# 3. Load the pre-trained Nano Classification Model
# We use 'n' (nano) because it trains much faster on Colab while still giving good results
model = YOLO('yolo11n-cls.pt')

# 4. Train the Model!
# IMPORTANT: The 'data' path must match the OUTPUT_DIR from Step 1
results = model.train(
    data='/content/drive/MyDrive/INFO813_Project/yolo_ready_data',
    epochs=20,          # 20 epochs is a good start. If accuracy is low, we can increase this later.
    imgsz=224,          # YOLO classification uses 224x224 image sizes
    batch=32,           # Processes 32 images at a time
    project='/content/drive/MyDrive/INFO813_Project/training_results',
    name='animal_classifier'
)

# 5. Evaluate the model on the Validation set
metrics = model.val()
print("--- TRAINING COMPLETE ---")
print(f"Top-1 Accuracy: {metrics.top1 * 100:.2f}%")
print(f"Top-5 Accuracy: {metrics.top5 * 100:.2f}%")